insert into client (firstname, lastname, middlename, cpf, address) values ('Annalee', 'Farrell', 'Denny', 2733754361, '7 Melby Trail');
insert into client (firstname, lastname, middlename, cpf, address) values ('Sarena', 'Shawdforth', 'Jeralee', 5677299867, '2 Schurz Trail');
insert into client (firstname, lastname, middlename, cpf, address) values ('Boycey', 'Josilowski', 'Lori', 7987689400, '194 Cardinal Drive');
insert into client (firstname, lastname, middlename, cpf, address) values ('Holmes', 'Blague', 'Sorcha', 9098449187, '83343 Glacier Hill Parkway');
insert into client (firstname, lastname, middlename, cpf, address) values ('Salvador', 'Hamilton', 'Kelly', 8376952800, '7 Lunder Hill');
insert into client (firstname, lastname, middlename, cpf, address) values ('Margeaux', 'Boddice', 'Vally', 8872476226, '1064 Hagan Center');
insert into client (firstname, lastname, middlename, cpf, address) values ('Saunder', 'Duffield', 'Tiphany', 9050730118, '7356 Ridgeway Alley');
insert into client (firstname, lastname, middlename, cpf, address) values ('Artemis', 'Mandrake', 'Belle', 2236051961, '47814 Hoard Park');
insert into client (firstname, lastname, middlename, cpf, address) values ('Haleigh', 'Hoyland', 'Dorolice', 10072350610, '067 Bartillon Trail');
insert into client (firstname, lastname, middlename, cpf, address) values ('Tobias', 'Easton', 'Elle', 8554319974, '74216 Miller Pass');
insert into client (firstname, lastname, middlename, cpf, address) values ('Margalo', 'Plowes', 'Wilona', 1774092914, '92 Crescent Oaks Pass');
insert into client (firstname, lastname, middlename, cpf, address) values ('Evy', 'Tatton', 'Marti', 5229110809, '81031 Rigney Crossing');
insert into client (firstname, lastname, middlename, cpf, address) values ('Cody', 'Moyler', 'Paolina', 8717169969, '21384 Nobel Park');
insert into client (firstname, lastname, middlename, cpf, address) values ('Francesco', 'Frankema', 'Sella', 10842998452, '06 Schlimgen Way');
insert into client (firstname, lastname, middlename, cpf, address) values ('Emalee', 'Havard', 'Maressa', 8043582790, '029 Mallard Center');
insert into client (firstname, lastname, middlename, cpf, address) values ('Xylia', 'Ungerecht', 'Rozella', 10770967422, '50987 Crowley Parkway');
insert into client (firstname, lastname, middlename, cpf, address) values ('Sherie', 'Pagden', 'Adelaide', 9702944367, '342 Oak Valley Parkway');
insert into client (firstname, lastname, middlename, cpf, address) values ('Willis', 'Streatley', 'Izabel', 4763520797, '2156 Knutson Drive');
insert into client (firstname, lastname, middlename, cpf, address) values ('Cristen', 'Esterbrook', 'Ninnetta', 9671905640, '94238 Northwestern Junction');
insert into client (firstname, lastname, middlename, cpf, address) values ('Randolph', 'Kensley', 'Eartha', 1859714544, '97 Towne Court');
insert into client (firstname, lastname, middlename, cpf, address) values ('Hewitt', 'MacLoughlin', 'Roseann', 4497139166, '7739 Hansons Crossing');
insert into client (firstname, lastname, middlename, cpf, address) values ('Pauline', 'Stollenwerck', 'Simonne', 8459142781, '15921 Mccormick Plaza');
insert into client (firstname, lastname, middlename, cpf, address) values ('Josie', 'Furney', 'Janeczka', 10827872632, '3 Roth Center');
insert into client (firstname, lastname, middlename, cpf, address) values ('Brook', 'Cicculini', 'Ainsley', 3993736205, '7137 Loomis Trail');
insert into client (firstname, lastname, middlename, cpf, address) values ('Ollie', 'Bowart', 'Gisele', 5999869086, '28088 Haas Junction');
insert into client (firstname, lastname, middlename, cpf, address) values ('Jerry', 'Lorenzini', 'Melita', 9868417549, '37387 Karstens Crossing');
insert into client (firstname, lastname, middlename, cpf, address) values ('Hana', 'Tomasini', 'Joelle', 3174211134, '63 Dawn Road');
insert into client (firstname, lastname, middlename, cpf, address) values ('Eva', 'Pessolt', 'Feliza', 1622931603, '65 Crescent Oaks Point');
insert into client (firstname, lastname, middlename, cpf, address) values ('Ado', 'Corneck', 'Charmane', 4229973565, '15524 Farragut Hill');
insert into client (firstname, lastname, middlename, cpf, address) values ('Brewster', 'Harsent', 'Midge', 9307508036, '158 Mosinee Crossing');
insert into client (firstname, lastname, middlename, cpf, address) values ('Caye', 'Hewkin', 'Teri', 5515417875, '24 La Follette Avenue');
insert into client (firstname, lastname, middlename, cpf, address) values ('Aleda', 'Stoddart', 'Raquel', 8487618203, '91 Michigan Center');
insert into client (firstname, lastname, middlename, cpf, address) values ('Wendeline', 'Sperling', 'Breena', 10923305788, '905 Iowa Parkway');
insert into client (firstname, lastname, middlename, cpf, address) values ('Tomi', 'Schiesterl', 'Max', 5977886917, '16 Myrtle Terrace');
insert into client (firstname, lastname, middlename, cpf, address) values ('Reynard', 'Suddards', 'Tove', 7728718747, '05598 Arrowood Way');
insert into client (firstname, lastname, middlename, cpf, address) values ('Stearne', 'Gerrets', 'Rebekah', 10095712310, '5 Forster Lane');
insert into client (firstname, lastname, middlename, cpf, address) values ('Guglielma', 'Bagge', 'Octavia', 9062053581, '88457 Anniversary Plaza');
insert into client (firstname, lastname, middlename, cpf, address) values ('Golda', 'Cameron', 'Jillian', 1635669017, '5407 Springs Terrace');
insert into client (firstname, lastname, middlename, cpf, address) values ('Tobe', 'Paton', 'Kalindi', 9999102609, '87350 Bluestem Plaza');
insert into client (firstname, lastname, middlename, cpf, address) values ('Giff', 'Thow', 'Chelsea', 10940480784, '5 Kingsford Trail');
insert into client (firstname, lastname, middlename, cpf, address) values ('Farra', 'Lace', 'Benni', 6370592831, '3 Portage Avenue');
insert into client (firstname, lastname, middlename, cpf, address) values ('Norrie', 'Neathway', 'Darleen', 10861636816, '43 Mayer Circle');
insert into client (firstname, lastname, middlename, cpf, address) values ('Pammy', 'Skirven', 'Iormina', 5466894519, '71299 Dunning Alley');
insert into client (firstname, lastname, middlename, cpf, address) values ('Isis', 'Fraulo', 'Ricky', 10712025712, '243 Amoth Road');
insert into client (firstname, lastname, middlename, cpf, address) values ('Madelyn', 'Glendenning', 'Tally', 7960401310, '44 Havey Lane');
insert into client (firstname, lastname, middlename, cpf, address) values ('Etheline', 'Burdfield', 'Shelley', 10025527876, '2 Victoria Circle');
insert into client (firstname, lastname, middlename, cpf, address) values ('Marina', 'Tongs', 'Kath', 10373471681, '20241 Barby Court');
insert into client (firstname, lastname, middlename, cpf, address) values ('Newton', 'Sorensen', 'Madelene', 10596893198, '25 Sugar Terrace');
insert into client (firstname, lastname, middlename, cpf, address) values ('Ricky', 'Shoveller', 'Daniele', 4972616886, '3 Carpenter Road');
insert into client (firstname, lastname, middlename, cpf, address) values ('Horatia', 'Knok', 'Mariele', 2472272206, '925 Laurel Place');
insert into client (firstname, lastname, middlename, cpf, address) values ('Katharina', 'Winchester', 'Britney', 5389300009, '5013 Jackson Parkway');
insert into client (firstname, lastname, middlename, cpf, address) values ('Evie', 'O''Gready', 'Herta', 1218480539, '51779 Coleman Place');
insert into client (firstname, lastname, middlename, cpf, address) values ('William', 'Cavy', 'Kristyn', 4392960241, '44262 Helena Center');
insert into client (firstname, lastname, middlename, cpf, address) values ('Quinta', 'Bosley', 'Tarah', 9118558486, '968 Sage Terrace');
insert into client (firstname, lastname, middlename, cpf, address) values ('Cecilia', 'Chaldecott', 'Beryl', 9937811620, '557 New Castle Junction');
insert into client (firstname, lastname, middlename, cpf, address) values ('Jobyna', 'Cholonin', 'Aggy', 1615432139, '86852 Cardinal Avenue');
insert into client (firstname, lastname, middlename, cpf, address) values ('Jordon', 'Glaisner', 'Merrily', 8028401120, '84 Eastlawn Circle');
insert into client (firstname, lastname, middlename, cpf, address) values ('Dolf', 'Son', 'Danyelle', 7478556645, '35228 Meadow Vale Parkway');
insert into client (firstname, lastname, middlename, cpf, address) values ('Jordanna', 'McNeillie', 'Friederike', 5458647545, '0432 Carey Way');
insert into client (firstname, lastname, middlename, cpf, address) values ('Abagael', 'Shuxsmith', 'Vivian', 4114883513, '67 Sage Avenue');
insert into client (firstname, lastname, middlename, cpf, address) values ('Klement', 'Varns', 'Desirae', 1054625617, '7 Esch Park');
insert into client (firstname, lastname, middlename, cpf, address) values ('Murdock', 'Jarrold', 'Flora', 3242724816, '7 Butterfield Circle');
insert into client (firstname, lastname, middlename, cpf, address) values ('Ayn', 'Osgood', 'Dynah', 6826354464, '650 Hoffman Street');
insert into client (firstname, lastname, middlename, cpf, address) values ('Shayne', 'Wayland', 'June', 3697586660, '3782 Helena Park');
insert into client (firstname, lastname, middlename, cpf, address) values ('Alberta', 'Rubinsky', 'Lynde', 5357839316, '24 John Wall Park');
insert into client (firstname, lastname, middlename, cpf, address) values ('Darb', 'Aird', 'Brenna', 2997799070, '9561 Cody Lane');
insert into client (firstname, lastname, middlename, cpf, address) values ('Chrissy', 'Crathern', 'Sandy', 48804052, '5030 Prentice Parkway');
insert into client (firstname, lastname, middlename, cpf, address) values ('Loy', 'Allcroft', 'Aeriela', 4889651105, '4 Spenser Alley');
insert into client (firstname, lastname, middlename, cpf, address) values ('Valentin', 'Saunt', 'Feliza', 9751597246, '134 Mandrake Terrace');
insert into client (firstname, lastname, middlename, cpf, address) values ('Kimmy', 'Pee', 'Wini', 3024240159, '9 Jay Avenue');
insert into client (firstname, lastname, middlename, cpf, address) values ('Ginger', 'Rappaport', 'Esme', 7903899015, '29 Blackbird Road');
insert into client (firstname, lastname, middlename, cpf, address) values ('Lorens', 'Jolley', 'Christabel', 5905908614, '9940 Sage Junction');
insert into client (firstname, lastname, middlename, cpf, address) values ('Nadeen', 'Devonish', 'Caye', 7975848194, '49932 Forest Dale Place');
insert into client (firstname, lastname, middlename, cpf, address) values ('Katerine', 'Bertwistle', 'Ettie', 7059996866, '59434 Dixon Terrace');
insert into client (firstname, lastname, middlename, cpf, address) values ('Meridith', 'Redfern', 'Deidre', 9927588801, '2959 Bay Parkway');
insert into client (firstname, lastname, middlename, cpf, address) values ('Brig', 'Westmoreland', 'Rubie', 11014629724, '3 Drewry Parkway');
insert into client (firstname, lastname, middlename, cpf, address) values ('Drusi', 'Cullabine', 'Cecilia', 5722578895, '3053 Loomis Junction');
insert into client (firstname, lastname, middlename, cpf, address) values ('Jaime', 'Preon', 'Tommy', 5872607493, '3 Grim Parkway');
insert into client (firstname, lastname, middlename, cpf, address) values ('Welch', 'Waylett', 'Ynes', 6898496067, '540 Anthes Center');
insert into client (firstname, lastname, middlename, cpf, address) values ('Joelle', 'Belfit', 'Clareta', 9707459221, '5 Warrior Lane');
insert into client (firstname, lastname, middlename, cpf, address) values ('Dannye', 'Franciotti', 'Nike', 1194326216, '0782 Pennsylvania Hill');
insert into client (firstname, lastname, middlename, cpf, address) values ('Egbert', 'Varsey', 'Martguerita', 3434490491, '887 Prentice Way');
insert into client (firstname, lastname, middlename, cpf, address) values ('Augustina', 'Goldin', 'Ellen', 4885142236, '6 Moulton Park');
insert into client (firstname, lastname, middlename, cpf, address) values ('Ronnie', 'Heigl', 'Dita', 8238412039, '3703 Oriole Way');
insert into client (firstname, lastname, middlename, cpf, address) values ('Kermy', 'Frowen', 'Keri', 3920160523, '4 Hudson Way');
insert into client (firstname, lastname, middlename, cpf, address) values ('Gwen', 'Whitten', 'Grete', 4218380984, '50 Ruskin Road');
insert into client (firstname, lastname, middlename, cpf, address) values ('Kienan', 'Szabo', 'Roseann', 937181260, '1828 Scott Plaza');
insert into client (firstname, lastname, middlename, cpf, address) values ('Solomon', 'McClosh', 'Delores', 6634925381, '256 Hagan Street');
insert into client (firstname, lastname, middlename, cpf, address) values ('Winn', 'Arden', 'Paulina', 3619371910, '9 Grayhawk Pass');
insert into client (firstname, lastname, middlename, cpf, address) values ('Mitchael', 'Coniff', 'Suzette', 2069779550, '90724 Lien Court');
insert into client (firstname, lastname, middlename, cpf, address) values ('Norby', 'Hunnawill', 'Noemi', 3357946405, '9628 Logan Road');
insert into client (firstname, lastname, middlename, cpf, address) values ('Zacharia', 'Meffan', 'Justine', 8684271595, '00 Amoth Road');
insert into client (firstname, lastname, middlename, cpf, address) values ('Camella', 'Cyples', 'Minerva', 1573818225, '9571 Merry Junction');
insert into client (firstname, lastname, middlename, cpf, address) values ('Merry', 'Badini', 'Theressa', 7644243424, '065 Browning Point');
insert into client (firstname, lastname, middlename, cpf, address) values ('Willem', 'Cage', 'Elnora', 2886958302, '0352 Rowland Court');
insert into client (firstname, lastname, middlename, cpf, address) values ('Briny', 'Benning', 'Vanny', 8304019585, '88810 Meadow Valley Trail');
insert into client (firstname, lastname, middlename, cpf, address) values ('Jamil', 'Hallan', 'Ellen', 8067551929, '45 Hauk Pass');
insert into client (firstname, lastname, middlename, cpf, address) values ('Rickie', 'Kolushev', 'Merrily', 489193777, '71 Eagle Crest Trail');
insert into client (firstname, lastname, middlename, cpf, address) values ('Jasmina', 'Risely', 'Gale', 9285343148, '414 Eagle Crest Court');
insert into client (firstname, lastname, middlename, cpf, address) values ('Conny', 'Grainge', 'Selie', 7788951836, '652 Orin Trail');
