insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Suspendisse accumsan tortor quis turpis.', 290.03);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 736.7);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Nullam varius.', 787.77);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Proin risus.', 868.68);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 944.5);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Aliquam erat volutpat. In congue. Etiam justo.', 420.88);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 429.06);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 454.56);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Nullam varius. Nulla facilisi.', 882.3);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Etiam justo. Etiam pretium iaculis justo.', 481.96);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Donec dapibus.', 735.52);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Mauris lacinia sapien quis libero.', 180.45);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 145.5);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 941.64);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Proin at turpis a pede posuere nonummy. Integer non velit.', 364.28);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 28.79);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Phasellus id sapien in sapien iaculis congue.', 517.8);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Maecenas pulvinar lobortis est.', 914.17);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Phasellus in felis. Donec semper sapien a libero.', 574.86);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 399.99);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', 900.88);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 843.02);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 669.5);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Morbi a ipsum. Integer a nibh.', 628.83);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 279.67);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 937.21);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Donec semper sapien a libero.', 146.32);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Nam dui.', 986.96);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 97.19);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Cras pellentesque volutpat dui.', 90.76);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Praesent blandit.', 617.7);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 323.5);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 69.69);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 302.18);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 329.39);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 947.53);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 144.02);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 822.14);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Vestibulum rutrum rutrum neque.', 855.01);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Aliquam erat volutpat. In congue.', 916.34);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 278.85);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 686.82);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 769.26);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Sed ante. Vivamus tortor.', 285.75);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 438.91);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Etiam faucibus cursus urna.', 962.9);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 473.82);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Sed ante.', 505.55);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Suspendisse potenti. In eleifend quam a odio.', 305.84);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Duis aliquam convallis nunc.', 735.22);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 138.79);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 997.12);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', 362.85);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 646.2);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 16.08);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', 170.67);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 308.21);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Morbi a ipsum. Integer a nibh. In quis justo.', 774.08);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 451.78);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Maecenas pulvinar lobortis est.', 727.19);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Suspendisse accumsan tortor quis turpis.', 287.58);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 138.03);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 638.78);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Nullam molestie nibh in lectus. Pellentesque at nulla.', 955.28);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Curabitur convallis.', 137.28);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 779.07);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Integer ac neque. Duis bibendum.', 892.24);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 968.34);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 758.52);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Fusce consequat.', 312.32);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 373.42);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 38.49);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 391.2);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'In hac habitasse platea dictumst.', 790.23);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 232.33);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', 629.36);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Duis bibendum. Morbi non quam nec dui luctus rutrum.', 498.19);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 942.04);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Duis ac nibh.', 873.64);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Fusce consequat.', 222.98);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Phasellus id sapien in sapien iaculis congue.', 628.72);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'In quis justo.', 833.68);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', 796.28);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 308.25);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 533.87);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Mauris lacinia sapien quis libero.', 62.81);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Sed vel enim sit amet nunc viverra dapibus.', 188.3);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Mauris ullamcorper purus sit amet nulla.', 307.85);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Duis consequat dui nec nisi volutpat eleifend.', 377.29);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Suspendisse ornare consequat lectus.', 407.29);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 371.59);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', 353.83);
insert into orders (orderstatus, orderdescription, freight) values ('Cancelado', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 944.3);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', 356.13);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 356.81);
insert into orders (orderstatus, orderdescription, freight) values ('Confirmado', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 836.32);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 269.84);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 353.95);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 507.89);
insert into orders (orderstatus, orderdescription, freight) values ('Em processamento', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 249.62);
