insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Tafinlar', false, 'Alimentos', 6.18, '4x5', '21906 Ridgeway Alley');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Vitamin E Moisture', true, 'Móveis', 8.49, '4x4', '057 Clarendon Way');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Children Acetaminophen Grape Flavored Chewable', true, 'Eletrônico', 6.71, '4x5', '0 Independence Plaza');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Metoprolol Tartrate', false, 'Alimentos', 7.54, '10x20', '33 Homewood Plaza');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Sunmark smooth antacid', true, 'Brinquedos', 7.56, '6x6', '932 Milwaukee Way');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Terazosin hydrochloride', true, 'Vestimenta', 6.97, '4x4', '80 Forster Pass');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Cough Complex', false, 'Eletrônico', 8.54, '10x10', '99225 Washington Alley');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Carbon Dioxide-Air Mixture', false, 'Eletrônico', 9.82, '4x4', '5 Doe Crossing Alley');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Low Dose Chewable Aspirin', true, 'Móveis', 9.26, '10x10', '48 Farragut Street');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Metformin Hydrochloride', true, 'Eletrônico', 9.64, '4x4', '3 Cottonwood Trail');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Donepezil Hydrochloride', true, 'Alimentos', 5.54, '4x4', '1 Stuart Point');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Sertraline Hydrochloride', true, 'Vestimenta', 4.56, '10x10', '44792 Cottonwood Junction');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('anti itch', true, 'Vestimenta', 4.48, '10x20', '3997 Morning Lane');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Pecan Pollen', false, 'Vestimenta', 9.7, '3x4', '656 Dryden Lane');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('topcare nite time cold and flu relief', true, 'Brinquedos', 3.8, '5x5', '959 2nd Lane');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Sertraline Hydrochloride', true, 'Móveis', 3.34, '4x5', '195 Prairie Rose Avenue');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Omeprazole', false, 'Brinquedos', 8.65, '3x4', '2 Garrison Court');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Zyprexa', true, 'Vestimenta', 5.98, '3x4', '50 Continental Place');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('NAPROXEN', false, 'Vestimenta', 2.08, '5x5', '5 Stuart Avenue');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('LESCOL', true, 'Móveis', 5.7, '6x6', '4372 Huxley Plaza');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Alprazolam', false, 'Móveis', 8.69, '3x4', '49220 Rockefeller Court');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Quetiapine Fumarate', true, 'Vestimenta', 6.08, '6x6', '40 Starling Circle');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Clear-Tone Antibacterial Hand', false, 'Eletrônico', 8.07, '3x4', '56 Scofield Alley');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Beautos Antibacterial Hand Sanitizer Lemon', true, 'Brinquedos', 4.52, '4x4', '938 Ridgeview Pass');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Recovatone', true, 'Eletrônico', 9.07, '5x5', '417 Mosinee Circle');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Head and Shoulders Conditioner', false, 'Eletrônico', 6.73, '5x5', '99602 Forster Center');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('skin elements liquid veil foundation broad spectrum SPF 25', true, 'Brinquedos', 7.43, '10x10', '87 Waywood Pass');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Trimethoprim', false, 'Brinquedos', 7.58, '10x20', '9 Kingsford Way');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Vitamin A and D', false, 'Vestimenta', 4.17, '5x5', '2958 Lunder Trail');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Viva', false, 'Alimentos', 4.2, '10x10', '259 Heffernan Lane');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Day Time Cold and Flu', true, 'Vestimenta', 3.88, '3x4', '9 Canary Terrace');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('COLGATE', true, 'Eletrônico', 9.6, '10x10', '00849 Jenna Plaza');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Fenofibrate', true, 'Móveis', 9.4, '6x6', '7 Union Street');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Carrot', true, 'Brinquedos', 5.7, '10x20', '48235 1st Terrace');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('HYDROCODONE BITARTRATE AND ACETAMINOPHEN', false, 'Brinquedos', 7.81, '4x5', '48 Eliot Park');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('ACNE MEDICATION 10', false, 'Vestimenta', 9.66, '10x10', '192 Rigney Trail');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Disopyramide Phosphate', true, 'Móveis', 2.55, '4x5', '09563 Melody Court');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('good neighbor pharmacy flu and severe cold', true, 'Móveis', 5.28, '6x6', '5 Becker Street');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Pantoprazole Sodium', false, 'Eletrônico', 7.58, '10x10', '817 Utah Pass');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Pain Relief', false, 'Eletrônico', 8.55, '10x20', '73551 Katie Park');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Icy Hot Medicated Roll Medium', true, 'Brinquedos', 8.11, '4x4', '53 Iowa Pass');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Clotrimazole', false, 'Eletrônico', 1.29, '6x6', '5608 Susan Street');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('CLE DE PEAU BEAUTE SILKY FOUNDATION I', false, 'Brinquedos', 9.02, '10x10', '20 Artisan Trail');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Sulfacetamide Sodium', false, 'Brinquedos', 6.95, '4x4', '50023 Crest Line Lane');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Metformin Hydrochloride', false, 'Alimentos', 8.3, '4x5', '5620 Caliangt Point');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Island Spring Antibacterial Body Wash', false, 'Móveis', 4.43, '5x5', '9510 7th Circle');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('TobraDex', true, 'Brinquedos', 7.8, '5x5', '147 1st Alley');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Shopko Antibacterial Hand Sanitizer', true, 'Alimentos', 6.47, '4x4', '594 Lakewood Court');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Appeal Non-Alcohol Foaming Hand Sanitizer', true, 'Brinquedos', 1.27, '6x6', '86903 Hazelcrest Crossing');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Quik Spray', true, 'Alimentos', 3.88, '4x4', '48 Oneill Park');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Levetiracetam', true, 'Alimentos', 7.24, '6x6', '2 Sutteridge Point');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('AcneVir', true, 'Alimentos', 1.75, '5x5', '47 Mcbride Road');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Sure Invisible Solid Fresh Scent', false, 'Móveis', 4.63, '4x4', '2 Corscot Trail');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Kiwi', false, 'Brinquedos', 8.72, '10x10', '4873 Swallow Park');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Meperidine Hydrochloride', true, 'Móveis', 3.46, '4x5', '8 Fuller Lane');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Acyclovir', false, 'Móveis', 1.56, '4x5', '551 Cordelia Street');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Childrens Dibromm Cold and Allergy', true, 'Alimentos', 2.47, '5x5', '80 Bellgrove Trail');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Neutrogena', true, 'Brinquedos', 5.88, '4x5', '180 Ruskin Avenue');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('BABY TINY COLD', true, 'Móveis', 1.74, '3x4', '855 Park Meadow Avenue');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('CYZONE', false, 'Vestimenta', 9.23, '3x4', '63976 Blackbird Trail');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Dicyclomine Hydrochloride', false, 'Vestimenta', 7.94, '4x5', '19101 3rd Court');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Dermasil', false, 'Alimentos', 3.93, '10x20', '6072 Red Cloud Center');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Hydrocodone Bitartrate and Acetaminophen', false, 'Móveis', 9.51, '10x20', '3475 Golf Course Crossing');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('UNIVERSAL BABY FRESH SCENT PETROLEUM', false, 'Alimentos', 7.32, '5x5', '74 Dahle Park');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Amlodipine Besylate', false, 'Eletrônico', 2.4, '3x4', '1365 Corben Road');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Musculus deltoideus comp. 8 Special Order', true, 'Vestimenta', 7.64, '4x4', '59453 Mccormick Pass');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Medline ReadyBath Luxe', true, 'Vestimenta', 3.98, '5x5', '82985 Fuller Pass');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Meijer Medicated Heat', true, 'Eletrônico', 8.07, '4x4', '749 Stuart Circle');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('V-COF', false, 'Eletrônico', 5.27, '5x5', '63085 Veith Junction');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('DR. S. WONGS ACNE TREATMENT SULPHUR', true, 'Eletrônico', 8.41, '4x5', '10 Carioca Hill');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Speed Stick', false, 'Vestimenta', 9.36, '3x4', '4 Glendale Parkway');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Erythromycin Base', false, 'Brinquedos', 5.35, '10x10', '6 Anthes Hill');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('MAXALT', false, 'Brinquedos', 4.71, '10x10', '49394 Bashford Trail');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Nasohist', false, 'Eletrônico', 3.49, '5x5', '309 Transport Parkway');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Carnitor SF', true, 'Brinquedos', 5.51, '10x10', '4 Buhler Way');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('SENSAI CONCEALER (BRUSH TYPE)', false, 'Móveis', 8.88, '10x20', '547 Warrior Court');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('alendronate sodium', false, 'Alimentos', 5.82, '5x5', '7567 Summerview Lane');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Nifedipine', true, 'Alimentos', 2.09, '10x10', '8798 Cambridge Terrace');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('LOESTRIN Fe 1.5/30', true, 'Eletrônico', 7.97, '3x4', '59 Dunning Pass');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Gumnumb Topical Anesthetic', false, 'Vestimenta', 4.24, '10x20', '688 Tennessee Crossing');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('OB Cleansing Towelette', false, 'Móveis', 3.93, '3x4', '82009 Ryan Hill');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Adderall', true, 'Vestimenta', 1.92, '4x5', '01011 School Hill');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Oxygen', true, 'Móveis', 4.19, '4x4', '97191 Heffernan Circle');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('ASSURED Antiseptic Wet Wipes Vitamin E and Aloe', true, 'Brinquedos', 1.42, '6x6', '3504 Corscot Plaza');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('PROMETHAZINE HYDROCHLORIDE', true, 'Móveis', 8.77, '4x5', '13 Merry Pass');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Synthroid', true, 'Vestimenta', 4.29, '10x10', '4 Mockingbird Lane');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Sertraline Hydrochloride Tablets', true, 'Eletrônico', 3.39, '4x5', '5835 Sunnyside Parkway');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Inclear', true, 'Brinquedos', 4.31, '3x4', '6 Declaration Center');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Hyosyne', false, 'Eletrônico', 7.1, '4x5', '22 Ludington Drive');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Pramipexole Dihydrochloride', false, 'Móveis', 6.37, '4x4', '99 Lunder Street');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Magnesium Sulfate', true, 'Alimentos', 4.17, '4x5', '367 Jackson Alley');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('benzonatate', true, 'Eletrônico', 8.05, '10x10', '44 Vernon Lane');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Promethazine HCl', true, 'Vestimenta', 2.34, '4x4', '034 Sugar Plaza');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Bacteria', false, 'Eletrônico', 1.8, '4x5', '70110 Golf View Drive');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('EQUUS CABALLUS SKIN', false, 'Alimentos', 1.71, '10x20', '5875 Mayer Hill');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Pleo Relivora', false, 'Eletrônico', 5.4, '3x4', '802 Barnett Road');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Bacitracin Zinc', true, 'Brinquedos', 2.55, '5x5', '959 Heath Hill');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('Crest Pro-Health', true, 'Móveis', 9.67, '3x4', '4 Moulton Center');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('By Pharmicell Lab Luxury Cell Performance Toner', true, 'Brinquedos', 1.03, '4x5', '56140 Claremont Terrace');
insert into product (productname, kidsclassification, category, rating, dimensions, address) values ('LBEL', true, 'Alimentos', 3.24, '5x5', '1052 Hooker Plaza');
