insert into productstorage (storagelocation, quantity) values ('031 Talmadge Plaza', 853);
insert into productstorage (storagelocation, quantity) values ('36 Hovde Trail', 831);
insert into productstorage (storagelocation, quantity) values ('506 Westerfield Lane', 490);
insert into productstorage (storagelocation, quantity) values ('8 Sachs Parkway', 46);
insert into productstorage (storagelocation, quantity) values ('1 Blaine Junction', 548);
insert into productstorage (storagelocation, quantity) values ('9 Little Fleur Center', 110);
insert into productstorage (storagelocation, quantity) values ('9048 Shopko Crossing', 322);
insert into productstorage (storagelocation, quantity) values ('0 Melody Terrace', 101);
insert into productstorage (storagelocation, quantity) values ('8927 Dahle Plaza', 95);
insert into productstorage (storagelocation, quantity) values ('44 Florence Point', 58);
insert into productstorage (storagelocation, quantity) values ('29670 Mccormick Hill', 948);
insert into productstorage (storagelocation, quantity) values ('49 Mariners Cove Avenue', 235);
insert into productstorage (storagelocation, quantity) values ('967 Graceland Street', 700);
insert into productstorage (storagelocation, quantity) values ('3759 Loeprich Way', 438);
insert into productstorage (storagelocation, quantity) values ('8 Birchwood Court', 671);
insert into productstorage (storagelocation, quantity) values ('534 Lake View Center', 983);
insert into productstorage (storagelocation, quantity) values ('8 Victoria Way', 929);
insert into productstorage (storagelocation, quantity) values ('9 Thierer Trail', 367);
insert into productstorage (storagelocation, quantity) values ('4213 Veith Parkway', 511);
insert into productstorage (storagelocation, quantity) values ('2 Nelson Plaza', 324);
insert into productstorage (storagelocation, quantity) values ('77849 Schurz Place', 327);
insert into productstorage (storagelocation, quantity) values ('99 Vernon Alley', 147);
insert into productstorage (storagelocation, quantity) values ('331 Morningstar Pass', 72);
insert into productstorage (storagelocation, quantity) values ('98 Sherman Trail', 454);
insert into productstorage (storagelocation, quantity) values ('1173 Sloan Lane', 556);
insert into productstorage (storagelocation, quantity) values ('04837 Mifflin Alley', 929);
insert into productstorage (storagelocation, quantity) values ('704 Florence Point', 742);
insert into productstorage (storagelocation, quantity) values ('867 Kipling Road', 831);
insert into productstorage (storagelocation, quantity) values ('337 Lien Crossing', 78);
insert into productstorage (storagelocation, quantity) values ('16737 Holy Cross Circle', 643);
insert into productstorage (storagelocation, quantity) values ('90552 Elka Alley', 182);
insert into productstorage (storagelocation, quantity) values ('202 Logan Drive', 733);
insert into productstorage (storagelocation, quantity) values ('860 Talisman Way', 462);
insert into productstorage (storagelocation, quantity) values ('442 Tomscot Junction', 75);
insert into productstorage (storagelocation, quantity) values ('37138 Garrison Plaza', 512);
insert into productstorage (storagelocation, quantity) values ('243 Monica Circle', 44);
insert into productstorage (storagelocation, quantity) values ('268 Bowman Crossing', 243);
insert into productstorage (storagelocation, quantity) values ('730 Park Meadow Way', 182);
insert into productstorage (storagelocation, quantity) values ('4921 American Ash Street', 402);
insert into productstorage (storagelocation, quantity) values ('308 Valley Edge Parkway', 604);
insert into productstorage (storagelocation, quantity) values ('78 Daystar Center', 930);
insert into productstorage (storagelocation, quantity) values ('394 Debs Lane', 228);
insert into productstorage (storagelocation, quantity) values ('64 Commercial Lane', 698);
insert into productstorage (storagelocation, quantity) values ('0 Macpherson Crossing', 413);
insert into productstorage (storagelocation, quantity) values ('011 Quincy Avenue', 719);
insert into productstorage (storagelocation, quantity) values ('089 Randy Pass', 751);
insert into productstorage (storagelocation, quantity) values ('37854 Erie Pass', 804);
insert into productstorage (storagelocation, quantity) values ('88 Hazelcrest Pass', 956);
insert into productstorage (storagelocation, quantity) values ('65 Truax Junction', 128);
insert into productstorage (storagelocation, quantity) values ('390 Knutson Trail', 930);
insert into productstorage (storagelocation, quantity) values ('6709 Warner Hill', 136);
insert into productstorage (storagelocation, quantity) values ('94 Badeau Pass', 647);
insert into productstorage (storagelocation, quantity) values ('02 Bayside Terrace', 711);
insert into productstorage (storagelocation, quantity) values ('03 Forest Alley', 47);
insert into productstorage (storagelocation, quantity) values ('482 Superior Hill', 903);
insert into productstorage (storagelocation, quantity) values ('968 Hoepker Parkway', 601);
insert into productstorage (storagelocation, quantity) values ('140 Badeau Alley', 629);
insert into productstorage (storagelocation, quantity) values ('38 Washington Lane', 469);
insert into productstorage (storagelocation, quantity) values ('8 Butternut Park', 432);
insert into productstorage (storagelocation, quantity) values ('535 Forest Crossing', 280);
insert into productstorage (storagelocation, quantity) values ('06 Blackbird Way', 425);
insert into productstorage (storagelocation, quantity) values ('9 Dahle Drive', 489);
insert into productstorage (storagelocation, quantity) values ('337 Weeping Birch Plaza', 903);
insert into productstorage (storagelocation, quantity) values ('1667 Warrior Drive', 564);
insert into productstorage (storagelocation, quantity) values ('82979 Mallory Park', 704);
insert into productstorage (storagelocation, quantity) values ('853 Arizona Circle', 318);
insert into productstorage (storagelocation, quantity) values ('6875 Continental Drive', 612);
insert into productstorage (storagelocation, quantity) values ('5 Main Point', 285);
insert into productstorage (storagelocation, quantity) values ('248 Paget Street', 821);
insert into productstorage (storagelocation, quantity) values ('086 Cardinal Court', 94);
insert into productstorage (storagelocation, quantity) values ('62352 Utah Court', 245);
insert into productstorage (storagelocation, quantity) values ('0452 Stoughton Way', 674);
insert into productstorage (storagelocation, quantity) values ('7 Pankratz Pass', 389);
insert into productstorage (storagelocation, quantity) values ('0404 Blackbird Trail', 455);
insert into productstorage (storagelocation, quantity) values ('398 Lien Place', 318);
insert into productstorage (storagelocation, quantity) values ('49 Cherokee Center', 725);
insert into productstorage (storagelocation, quantity) values ('6 Red Cloud Park', 186);
insert into productstorage (storagelocation, quantity) values ('4657 Center Crossing', 750);
insert into productstorage (storagelocation, quantity) values ('0328 Sachs Alley', 933);
insert into productstorage (storagelocation, quantity) values ('195 Lakeland Terrace', 191);
insert into productstorage (storagelocation, quantity) values ('94 Commercial Center', 827);
insert into productstorage (storagelocation, quantity) values ('7 Village Way', 105);
insert into productstorage (storagelocation, quantity) values ('072 Hoffman Lane', 130);
insert into productstorage (storagelocation, quantity) values ('12567 Packers Park', 719);
insert into productstorage (storagelocation, quantity) values ('2 Nelson Crossing', 563);
insert into productstorage (storagelocation, quantity) values ('0168 Bayside Trail', 639);
insert into productstorage (storagelocation, quantity) values ('4 Goodland Court', 252);
insert into productstorage (storagelocation, quantity) values ('36266 Manufacturers Point', 587);
insert into productstorage (storagelocation, quantity) values ('2738 Golden Leaf Park', 884);
insert into productstorage (storagelocation, quantity) values ('5 Grasskamp Avenue', 785);
insert into productstorage (storagelocation, quantity) values ('3 Mesta Road', 190);
insert into productstorage (storagelocation, quantity) values ('5237 8th Street', 812);
insert into productstorage (storagelocation, quantity) values ('69 Gale Junction', 787);
insert into productstorage (storagelocation, quantity) values ('0 Mesta Circle', 933);
insert into productstorage (storagelocation, quantity) values ('90774 Browning Place', 899);
insert into productstorage (storagelocation, quantity) values ('61797 Sachtjen Crossing', 309);
insert into productstorage (storagelocation, quantity) values ('85 Dorton Pass', 301);
insert into productstorage (storagelocation, quantity) values ('82211 Corben Crossing', 902);
insert into productstorage (storagelocation, quantity) values ('75 Mcbride Crossing', 531);
insert into productstorage (storagelocation, quantity) values ('7 Oxford Center', 167);
