insert into productorder (productquantity, productstatus) values (445, 'Disponível');
insert into productorder (productquantity, productstatus) values (24, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (167, 'Disponível');
insert into productorder (productquantity, productstatus) values (810, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (737, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (632, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (185, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (661, 'Disponível');
insert into productorder (productquantity, productstatus) values (429, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (183, 'Disponível');
insert into productorder (productquantity, productstatus) values (869, 'Disponível');
insert into productorder (productquantity, productstatus) values (579, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (214, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (345, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (747, 'Disponível');
insert into productorder (productquantity, productstatus) values (328, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (933, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (216, 'Disponível');
insert into productorder (productquantity, productstatus) values (428, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (791, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (811, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (404, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (92, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (531, 'Disponível');
insert into productorder (productquantity, productstatus) values (890, 'Disponível');
insert into productorder (productquantity, productstatus) values (130, 'Disponível');
insert into productorder (productquantity, productstatus) values (441, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (674, 'Disponível');
insert into productorder (productquantity, productstatus) values (817, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (170, 'Disponível');
insert into productorder (productquantity, productstatus) values (424, 'Disponível');
insert into productorder (productquantity, productstatus) values (482, 'Disponível');
insert into productorder (productquantity, productstatus) values (851, 'Disponível');
insert into productorder (productquantity, productstatus) values (533, 'Disponível');
insert into productorder (productquantity, productstatus) values (284, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (378, 'Disponível');
insert into productorder (productquantity, productstatus) values (396, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (24, 'Disponível');
insert into productorder (productquantity, productstatus) values (401, 'Disponível');
insert into productorder (productquantity, productstatus) values (409, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (585, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (491, 'Disponível');
insert into productorder (productquantity, productstatus) values (901, 'Disponível');
insert into productorder (productquantity, productstatus) values (721, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (296, 'Disponível');
insert into productorder (productquantity, productstatus) values (904, 'Disponível');
insert into productorder (productquantity, productstatus) values (792, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (589, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (824, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (725, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (795, 'Disponível');
insert into productorder (productquantity, productstatus) values (529, 'Disponível');
insert into productorder (productquantity, productstatus) values (284, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (677, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (328, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (305, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (320, 'Disponível');
insert into productorder (productquantity, productstatus) values (805, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (153, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (29, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (3, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (958, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (968, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (679, 'Disponível');
insert into productorder (productquantity, productstatus) values (493, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (824, 'Disponível');
insert into productorder (productquantity, productstatus) values (615, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (890, 'Disponível');
insert into productorder (productquantity, productstatus) values (833, 'Disponível');
insert into productorder (productquantity, productstatus) values (866, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (742, 'Disponível');
insert into productorder (productquantity, productstatus) values (600, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (155, 'Disponível');
insert into productorder (productquantity, productstatus) values (655, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (919, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (830, 'Disponível');
insert into productorder (productquantity, productstatus) values (368, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (631, 'Disponível');
insert into productorder (productquantity, productstatus) values (109, 'Disponível');
insert into productorder (productquantity, productstatus) values (46, 'Disponível');
insert into productorder (productquantity, productstatus) values (981, 'Disponível');
insert into productorder (productquantity, productstatus) values (71, 'Disponível');
insert into productorder (productquantity, productstatus) values (752, 'Disponível');
insert into productorder (productquantity, productstatus) values (514, 'Disponível');
insert into productorder (productquantity, productstatus) values (477, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (518, 'Disponível');
insert into productorder (productquantity, productstatus) values (531, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (964, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (974, 'Disponível');
insert into productorder (productquantity, productstatus) values (831, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (280, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (742, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (126, 'Disponível');
insert into productorder (productquantity, productstatus) values (956, 'Disponível');
insert into productorder (productquantity, productstatus) values (914, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (360, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (536, 'Disponível');
insert into productorder (productquantity, productstatus) values (45, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (780, 'Sem estoque');
insert into productorder (productquantity, productstatus) values (773, 'Disponível');
